### ISSUE TITLE
App is not compatible with NC18 / files_text

### ISSUE THREAD

**Issue by zerknorscht** [nextcloud/cms_pico#116]
As Text is the default Editor for markdown files in Nextcloud 18, no other Editor is working out of the Box and the Text App is breaking the fomatting of the yaml headers, wich leads to broken pages I cannot figure out, how to use cms_pico without editing it through an external editor.
Maybe I am missing something here, but isn't the point of having a cms integration in NC being able to edit it from WITHIN Nextcloud?

I cannot get it to work right for me and I think it is a pretty big Issue....
The real Problem seems to be about the Text-App, not about pico, but maybe some devs from both apps could get in touch wich each other (if it's not being done allready)
I think I saw an Issue about this in the Text App, but from their perspective it seems to be a minor issue...  from the usability of cms_pico however it seems to be rather major, right?

**Comment by PhrozenByte** [comment]
This is indeed an issue with Nextcloud's Text app, not with Pico CMS for Nextcloud. The issue is known. See https://github.com/nextcloud/text/issues/418 and https://github.com/nextcloud/text/issues/145

**Comment by Prog1563** [comment]
Just a bump that the title might benefit from being more general. This issue affects all versions of Nextcloud from 18-21.0.2 that have the new version of the text app, not just NC 18

**Comment by nooblag** [comment]
I agree. In the meantime, is there a way you could associate Pico's files to open with Plain Text Editor or a Markdown editor that doesn't break things in the meantime? We still have this issue on Nextcloud 21.0.2.

**Comment by PhrozenByte** [comment]
You can install Nextcloud's Markdown editor to associate `.md` files with this editor instead, see https://github.com/icewind1991/files_markdown#behaviors on how to open these files with Markdown editor instead then. The easiest solution is to disable Nextcloud's Text app.

**Comment by nooblag** [comment]
Thanks for that. Yes, we could disable the Text app, but we use that. I think in the absence of a fix either there or here, we'll probably have to resort to the "right click, open with plain text editor" workaround, which isn't the best, but it will do.

**Comment by PhrozenByte** [comment]
Unfortunately we can't do anything about this. I'm not sure whether this is caused by how Nextcloud handles file associations, or whether it is caused by the Text app. You might wanna open a feature request on Nextcloud's server repo to implement a "default app" chooser or something?

**Comment by asereq** [comment]
I think this was solved few months ago when https://github.com/nextcloud/text/issues/145 was fixed.

**Comment by nooblag** [comment]
Unfortunately no, and worse, this app doesn't work at all anymore on NC 27 and newer.

**Comment by PhrozenByte** [comment]
> Has anyone tested this more recently, with newer versions of Nextcloud and the Text app, since both https://github.com/nextcloud/text/pull/2751 and
https://github.com/nextcloud/text/pull/3460 were merged?

There were indeed very, very major improvements towards compatibility. Some rather small issues remain (some of which I'd say don't matter much in practice), thus we should keep this issue open, just to keep track of that as of now rather minor fact.
